name: Run app.py and write the output to README

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      
    - name: Install Cloudflared
      run: |
        wget https://bin.equinox.io/c/VdrWdbjqyF/cloudflared-stable-linux-amd64.deb
        sudo dpkg -i cloudflared-stable-linux-amd64.deb

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run app.py
      id: app
      run: echo "::set-output name=URL::$(python app.py)"

    - name: Write output to README
      run: |
        echo "${{ steps.app.outputs.URL }}" >> README.md
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "GitHub Actions"
        git add README.md
        git commit -m "Update README with the output URL"
        git push
