name: News Update

on:
  workflow_dispatch: # manual trigger 

jobs:
  update-readme-with-news:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 # important to be able to update the README file

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9' # or any version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi # install dependencies if there are any

    - name: Run news updater
      run: |
        python news-updater.py # run our python script to update the README
