name: Cloudflared Flask App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install cloudflared
      run: |
        wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe
        ./cloudflared-windows-amd64.exe --version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Flask App
      run: |
        $env:FLASK_APP="app.py"
        flask run > output.txt 2>&1 &

    - name: Extract URL and Write to file
      run: |
        Start-Sleep -s 10
        $content = Get-Content output.txt -Raw
        $url = [regex]::match($content, 'https://[^\s]+.trycloudflare.com').value
        echo $url | Out-File -FilePath public_url.txt

    - name: Upload URL file
      uses: actions/upload-artifact@v2
      with:
        name: url-file
        path: public_url.txt
